# Generated by Django 4.1.5 on 2023-01-25 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-pk"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
